/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import com.toedter.calendar.JDayChooser;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import proyectoagendaroller.Alumno;
import proyectoagendaroller.Cita;
import proyectoagendaroller.*;
import proyectoagendaroller.Instructor;
import proyectoagendaroller.Perfiles;
public class AgendarCitas extends javax.swing.JFrame {

    private String nombreInstructorSeleccionado;

    /**
     * Creates new form AgendarCitas
     */
    
    public AgendarCitas() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNombreInstructor = new javax.swing.JLabel();
        listaInstructores = new javax.swing.JComboBox<>();
        lblCedulaAlumno = new javax.swing.JLabel();
        txtCedulaAlumno = new javax.swing.JTextField();
        lblLugar = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        lblNivel = new javax.swing.JLabel();
        txtNivel = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblHoraCita = new javax.swing.JLabel();
        txtHoraCita = new javax.swing.JTextField();
        lblAgendrarCitas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        lblFecha = new javax.swing.JLabel();
        Volver = new javax.swing.JLabel();
        Cerrar = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Imagenes/FondoConsultas.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreInstructor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreInstructor.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreInstructor.setText("Nombre Instructor:");
        jPanel2.add(lblNombreInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 126, -1, -1));

        listaInstructores.setModel(new javax.swing.DefaultComboBoxModel<>(Perfiles.nombresInstructores()));
        listaInstructores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaInstructoresActionPerformed(evt);
            }
        });
        jPanel2.add(listaInstructores, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 148, 227, -1));

        lblCedulaAlumno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCedulaAlumno.setForeground(new java.awt.Color(255, 255, 255));
        lblCedulaAlumno.setText("Cedula Alumno:");
        jPanel2.add(lblCedulaAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 179, -1, -1));

        txtCedulaAlumno.setText("IngresaCedula");
        jPanel2.add(txtCedulaAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 135, -1));

        lblLugar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLugar.setForeground(new java.awt.Color(255, 255, 255));
        lblLugar.setText("Lugar:");
        jPanel2.add(lblLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 204, -1, -1));

        txtLugar.setText("Ingresa Lugar");
        jPanel2.add(txtLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        lblNivel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNivel.setForeground(new java.awt.Color(255, 255, 255));
        lblNivel.setText("Nivel:");
        jPanel2.add(lblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 238, -1, -1));

        txtNivel.setText("Ingresa Nivel");
        jPanel2.add(txtNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        btnGuardar.setText("Guardar Cita");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 311, 112, 50));

        lblHoraCita.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHoraCita.setForeground(new java.awt.Color(255, 255, 255));
        lblHoraCita.setText("Hora Cita:");
        jPanel2.add(lblHoraCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 275, -1, -1));

        txtHoraCita.setText("Ingresa Hora 1-24");
        jPanel2.add(txtHoraCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        lblAgendrarCitas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAgendrarCitas.setForeground(new java.awt.Color(255, 255, 255));
        lblAgendrarCitas.setText("Agendar Cita");
        jPanel2.add(lblAgendrarCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Imagenes/FondoConsultas.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -70, -1, 910));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 370, 400));
        jPanel1.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 640, 500));

        lblFecha.setText("Selecciona una fecha:");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Imagenes/VolverBlanco.png"))); // NOI18N
        Volver.setMaximumSize(new java.awt.Dimension(32, 33));
        Volver.setMinimumSize(new java.awt.Dimension(32, 33));
        Volver.setPreferredSize(new java.awt.Dimension(32, 33));
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VolverMouseExited(evt);
            }
        });
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Imagenes/Cerrar.png"))); // NOI18N
        Cerrar.setMaximumSize(new java.awt.Dimension(32, 33));
        Cerrar.setMinimumSize(new java.awt.Dimension(32, 33));
        Cerrar.setPreferredSize(new java.awt.Dimension(32, 33));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarMouseExited(evt);
            }
        });
        jPanel1.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, -1, -1));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Imagenes/Minimizar.png"))); // NOI18N
        Minimizar.setMaximumSize(new java.awt.Dimension(32, 33));
        Minimizar.setMinimumSize(new java.awt.Dimension(32, 33));
        Minimizar.setPreferredSize(new java.awt.Dimension(32, 33));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizarMouseExited(evt);
            }
        });
        jPanel1.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Imagenes/FondoConsultas.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 910));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaInstructoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaInstructoresActionPerformed
        // TODO add your handling code here:
        // Obtener el nombre del instructor seleccionado
        String nombreInstructorSeleccionado = (String) listaInstructores.getSelectedItem();
        // Puedes imprimir el nombre para verificar si se obtuvo correctamente
        System.out.println("Instructor seleccionado: " + nombreInstructorSeleccionado);
        this.nombreInstructorSeleccionado = nombreInstructorSeleccionado;
    }//GEN-LAST:event_listaInstructoresActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        // Verificar si se ha seleccionado un instructor antes de intentar usar el nombre
        if (nombreInstructorSeleccionado != null && !nombreInstructorSeleccionado.isEmpty()) {
        // se capturan los datos que nos proporciona el usuario para crear la cita
        //
            Instructor buscadoInstructor = (Instructor)Perfiles.buscarPerfilNombre(nombreInstructorSeleccionado);
            Alumno buscadoAlumno = (Alumno)Perfiles.buscarPerfilCedula(Integer.getInteger(txtCedulaAlumno.getText()));
            Date fechaElegida = jCalendar1.getDate();
            int horaElegida = Integer.getInteger(txtHoraCita.getText());
            String lugarElegido = txtLugar.getText();
            String nivelElegido = txtNivel.getText();
            String estadoXDefecto = "Pendiente";
            
            //datos para modificar el instructor            
            int[] diasDisponiblesInstructor = buscadoInstructor.getDiasDisponiblesMarca();
            int[] horasDisponiblesInstructor = buscadoInstructor.getHorasDisponibles();
            //datos para modificar el alumno
            int[] diaClaseAlumno = buscadoAlumno.getDiaClaseMarca();
            int[] horasPendientesAlumno = buscadoAlumno.getHoraClase();
            
            String dia = jCalendar1.getDayChooser().toString();
            System.out.println(dia);
            boolean pasoDiaDisp = false;
            switch (dia) {
                case "lunes":
                      if (diasDisponiblesInstructor[0]==1) {
                          pasoDiaDisp = true;
                          diasDisponiblesInstructor[0]= 0;
                          horasDisponiblesInstructor[0]=0;
                          diaClaseAlumno[0]= 1;
                          horasPendientesAlumno[0]= horaElegida;
                    }
                 
                    
                    break;
                case "martes":
                    if (diasDisponiblesInstructor[1]==1) {
                          pasoDiaDisp = true; 
                          diasDisponiblesInstructor[1]= 0;
                          horasDisponiblesInstructor[1]=0;
                          diaClaseAlumno[1]= 1;
                          horasPendientesAlumno[1]= horaElegida;
                    }
                    
                    break;
                case "miercoles":
                    if (diasDisponiblesInstructor[2]==1) {
                          pasoDiaDisp = true;   
                          diasDisponiblesInstructor[2]= 0;
                          horasDisponiblesInstructor[2]=0;
                          diaClaseAlumno[2]= 1;
                          horasPendientesAlumno[2]= horaElegida;
                    }
                    
                    break;
                case "jueves":
                    if (diasDisponiblesInstructor[3]==1) {
                          pasoDiaDisp = true;  
                          diasDisponiblesInstructor[3]= 0;
                          horasDisponiblesInstructor[3]=0;
                          diaClaseAlumno[3]= 1;
                          horasPendientesAlumno[3]= horaElegida;
                    }
                    
                    break;
                case "viernes":
                    if (diasDisponiblesInstructor[4]==1) {
                          pasoDiaDisp = true; 
                          diasDisponiblesInstructor[4]= 0;
                          horasDisponiblesInstructor[4]=0;
                          diaClaseAlumno[4]= 1;
                          horasPendientesAlumno[4]= horaElegida;
                    }
                    
                    break;
                case "sabado":
                    if (diasDisponiblesInstructor[5]==1) {
                          pasoDiaDisp = true;
                          diasDisponiblesInstructor[5]= 0;
                          horasDisponiblesInstructor[5]=0;
                          diaClaseAlumno[5]= 1;
                          horasPendientesAlumno[5]= horaElegida;
                    }
                    
                    break;
                case "domingo":
                    if (diasDisponiblesInstructor[6]==1) {
                          pasoDiaDisp = true;
                          diasDisponiblesInstructor[6]= 0;
                          horasDisponiblesInstructor[6]=0;
                          diaClaseAlumno[6]= 1;
                          horasPendientesAlumno[6]= horaElegida;
                    }
                    
                    break;
                default:
                    throw new AssertionError();
            }
            buscadoAlumno.setDiaClaseMarca(diaClaseAlumno);
            buscadoAlumno.setHoraClase(horasPendientesAlumno);
            buscadoAlumno.setNivel(nivelElegido);
            buscadoInstructor.setDiasDisponiblesMarca(diasDisponiblesInstructor);
            buscadoInstructor.setHorasDisponibles(horasDisponiblesInstructor);
            Perfiles.modificarPerfilUsuario(buscadoAlumno);
            Perfiles.modificarPerfilUsuario(buscadoInstructor);
            
            //creacion de cita
            
            Cita nuevaCita = new Cita(buscadoInstructor.getCedula(), buscadoAlumno.getCedula(), fechaElegida, horaElegida, lugarElegido, nivelElegido, estadoXDefecto);
            
            GestorCitas gestorCitas= new GestorCitas();
                    gestorCitas.guardarCitasRegistradas(nuevaCita);
            
            JOptionPane.showMessageDialog(null, "Se ha guardado la cita: \n"+nuevaCita.mostrarCita());
        // Resto del código para manejar la nueva cita
        } else {
            // Mostrar un mensaje de error o realizar alguna acción apropiada si no se ha seleccionado un instructor
            System.out.println("Error: No se ha seleccionado un instructor.");
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseClicked
        dispose();
        JFrame Menu = new Menu();
        Menu.setVisible(true);
    }//GEN-LAST:event_VolverMouseClicked

    private void VolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseEntered
        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Imagenes/VolverVerde.png"))); // NOI18N
    }//GEN-LAST:event_VolverMouseEntered

    private void VolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseExited
        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Imagenes/VolverBlanco.png"))); // NOI18N
        // TODO add your handling code here:
    }//GEN-LAST:event_VolverMouseExited

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        dispose();
    }//GEN-LAST:event_CerrarMouseClicked

    private void CerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseEntered
        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Imagenes/cerrarrosa.png"))); // NOI18N
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarMouseEntered

    private void CerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseExited
        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Imagenes/Cerrar.png")));
    }//GEN-LAST:event_CerrarMouseExited

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void MinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseEntered
        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Imagenes/Minimizarverde.png"))); // NOI18N
    }//GEN-LAST:event_MinimizarMouseEntered

    private void MinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseExited
        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Imagenes/Minimizar.png"))); // NOI18N
        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizarMouseExited

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendarCitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cerrar;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel Volver;
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAgendrarCitas;
    private javax.swing.JLabel lblCedulaAlumno;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHoraCita;
    private javax.swing.JLabel lblLugar;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNombreInstructor;
    private javax.swing.JComboBox<String> listaInstructores;
    private javax.swing.JTextField txtCedulaAlumno;
    private javax.swing.JTextField txtHoraCita;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNivel;
    // End of variables declaration//GEN-END:variables
}
